### ISSUE TITLE
Open new Root from existing Root (and other O_PATH sub-opens)

### ISSUE THREAD

**Issue by shlevy** [openSUSE/libpathrs#26]
Would be great if we could safely open another dirfd descending from an existing one, or other O_PATH-style opens for `AT_EMPTY_PATH`-style usages.

**Comment by cyphar** [comment]
I did think about adding this initially, but the main thing that gave me pause was the following:

If we assume the rootfs is untrusted (which is why you'd use this library), we're going to end up giving `Root` handles that are inside attacker-controlled directories. This is something that is pretty hard to defend against, even at the best of times. Now, ultimately they (likely) couldn't trick you into opening files which are outside of their sphere of influence (all of the obvious "move the root directory" tricks will be detected with `openat2` and probably with the emulated resolver too), so maybe this isn't a massive concern -- but it does make me worry a bit. 

It should be noted that if you really want to, you can actually do this today by doing something like:

```rust
let handle = root.resolve("/foo/bar");
let new_root = Root::from_file_unchecked(handle.into_file());
```

And `Root::from_file_unchecked` is very much intended for the `AT_EMPTY_PATH`-style usage. The "unchecked" sounds scary but that's just because at the moment we don't do any checks on the file descriptor you provide (in the future I'll add a `Root::from_file` which checks that the file is actually a directory and a few other minor checks like the open mode).

**Comment by shlevy** [comment]
Ah, I see, thanks! I'm realizing now that my use cases are a bit different... I'm basically interested in capability-esque use cases where the dirfd is trusted but the user of it isn't. I also would rather `LOOKUP_BENEATH` than `LOOKUP_IN_ROOT` for similar reasons. Maybe down the road it might make sense to split the high level container-oriented interface and the low-level primitives?

**Comment by cyphar** [comment]
> I'm basically interested in capability-esque use cases where the dirfd is trusted but the user of it isn't.

Yeah, this was an idea that has been brought up a lot but unfortunately such capability-based systems are not currently (trivially) enforceable under Linux -- you can get outside the directory if you open a sub-path. There are some ways you could do it, but they're not exactly pretty (create a process which `pivot_root`s to the `dirfd`, then open the path, then pass it back to the process) and you'd need to figure out a way to force a process to only use those primitives rather than `open`.

> Maybe down the road it might make sense to split the high level container-oriented interface and the low-level primitives?

Yeah I'll look into that in the future, though it should be noted that while container runtimes are one of the key use-cases for libpathrs there are lots of other applications that need something like this (file servers for instance).

**Comment by cyphar** [comment]
Since this doesn't quite match `libpathrs`'s intended use-case, I'll close this. Feel free to comment if you'd like me to reopen it.
